#!/bin/sh

# ==============================================================================
# 1. BIẾN MÔI TRƯỜNG & ĐƯỜNG DẪN PATH
# ==============================================================================
# Xuất đường dẫn script cá nhân nếu cần
# export PATH="$HOME/.local/bin/scripts:$PATH"

# ==============================================================================
# 2. CẤU HÌNH BỘ GÕ TIẾNG VIỆT (FCITX5)
# ==============================================================================
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
export INPUT_METHOD=fcitx5
export SDL_IM_MODULE=fcitx

