#!/bin/sh
# Script tạo preview cho lf

set -C -f
IFS="$(printf '%b_' '\n')"
IFS="${IFS%_}"

image() {
  if [ -f "$1" ] && [ -n "$DISPLAY" ] && command -V ueberzug >/dev/null 2>&1; then
    printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$4" "$5" "$(($2 - 1))" "$(($3 - 1))" "$1" >"$FIFO_UEBERZUG"
  else
    mediainfo "$6"
  fi
}

case "$(file --dereference --brief --mime-type -- "$1")" in
image/*) image "$1" "$2" "$3" "$4" "$5" "$1" ;;
text/* | */xml | application/json) bat -p --theme ansi --terminal-width "$(($4 - 2))" -f "$1" ;;
video/*)
  CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
  [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
  image "$CACHE" "$2" "$3" "$4" "$5" "$1"
  ;;
*/pdf)
  CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
  [ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
  image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
  ;;
application/x-7z-compressed | application/*zip | application/x-rar)
  # Tự động detect part .001 để preview đúng
  target="$1"
  if echo "$1" | grep -qE "\.[0-9]{3}$"; then
    base="${1%.*}"
    [ -f "${base}.001" ] && target="${base}.001"
  fi

  # Dùng 7z l để liệt kê, lọc bỏ header thừa, hiển thị dạng cây thư mục nếu có thể
  7z l "$target" | sed -n '/Date      Time/,$p' | head -n 200
  exit 1
  ;;

*) echo "No preview" ;;
esac
exit 1
