# 0: Telex, 1: Telex 2, 2: Telex 3, 3: VNI
InputMethod=0
# Modern tone mark placement (oà/oá instead of òa/óa)
ModernStyle=True
# Auto restore word on backspace / English spell checking
AutoRestoreWord=True
# Free tone marking anywhere in word
FreeMarking=True
