# Show input method information popup on screen when switching
ShowInputMethodInformation=True
# Font
Font="Sans 11"
# Tray Font
TrayFont="Sans 10"
# Prefer text icon in tray
PreferTextIcon=True
# Use dark mode / system color
UseDarkTheme=True
