# Auto-generated by theme-set — KHÔNG sửa tay
# Nguồn sự thật: ~/.config/theme/colors/current.conf
# Được chèn vào dunstrc giữa 2 marker BEGIN/END THEME MANAGED BLOCK

[urgency_low]
    background = "#${BG}"
    foreground = "#${FG}"
    frame_color = "#${COLOR8}"
    timeout = 5

[urgency_normal]
    background = "#${BG}"
    foreground = "#${FG}"
    frame_color = "#${ACCENT}"
    timeout = 5

[urgency_critical]
    background = "#${COLOR1}"
    foreground = "#${COLOR15}"
    frame_color = "#${COLOR1}"
    timeout = 0
