# ==============================================================================
# GTK Settings — Auto-generated by Ka Appearance Engine
# Single Source of Truth: ~/.config/theme/colors/current.conf
# ==============================================================================

[Settings]
gtk-theme-name=${GTK_THEME_BASE}
gtk-application-prefer-dark-theme=${GTK_PREFER_DARK}
gtk-icon-theme-name=${ICON_THEME}
gtk-font-name=${FONT_UI} ${FONT_UI_SIZE}
gtk-cursor-theme-name=${CURSOR_THEME}
gtk-cursor-theme-size=${CURSOR_SIZE}

gtk-button-images=0
gtk-menu-images=0
gtk-enable-event-sounds=0
gtk-enable-input-feedback-sounds=0

gtk-toolbar-style=GTK_TOOLBAR_TEXT
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR

gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintmedium
gtk-xft-rgba=rgb
