/* ==============================================================================
 * Universal GTK Colors — Auto-generated by Ka Appearance Engine
 * Single Source of Truth: ~/.config/theme/colors/current.conf
 * Target: ~/.config/gtk-3.0/gtk.css & ~/.config/gtk-4.0/gtk.css
 * ============================================================================== */

@define-color theme_bg_color #${BG};
@define-color theme_fg_color #${FG};
@define-color theme_base_color #${BG};
@define-color theme_text_color #${FG};
@define-color theme_selected_bg_color #${ACCENT};
@define-color theme_selected_fg_color #${BG};

/* Extended semantic colors for cards, headers, popovers */
@define-color card_bg_color #${SURFACE};
@define-color headerbar_bg_color #${SURFACE};
@define-color headerbar_fg_color #${FG};
@define-color border_color #${BORDER};
@define-color popover_bg_color #${SURFACE};
@define-color popover_fg_color #${FG};

@define-color success_color #${COLOR2};
@define-color warning_color #${COLOR3};
@define-color error_color #${COLOR1};

/* Omarchy / Suckless aesthetic standards: clean zero-radius */
window, dialog, popover {
    border-radius: 0px;
    background-color: @theme_bg_color;
    color: @theme_fg_color;
}

headerbar, toolbar {
    border-radius: 0px;
    background-color: @headerbar_bg_color;
    color: @headerbar_fg_color;
}

.view, textview text, entry, treeview {
    background-color: @theme_base_color;
    color: @theme_text_color;
}
