/* Auto-generated by theme-set — KHÔNG sửa tay */
/* Nguồn sự thật: ~/.config/theme/colors/current.conf */

* {
    /* Base colors from theme palette */
    bg:       #${BG};
    bg-alt:   #${COLOR0};
    fg:       #${FG};
    fg-dim:   #${COLOR7};
    accent:   #${ACCENT};
    red:      #${COLOR1};
    green:    #${COLOR2};

    /* Rofi semantic colors with alpha */
    background-color: @bg;
    text-color:       @fg;
}

window {
    border-color: @accent;
}

element selected {
    background-color: @accent;
    text-color:       #${BG};
}

element-text {
    background-color: transparent;
    text-color:       inherit;
}

element-icon {
    background-color: transparent;
}
