/* Auto-generated by theme-set — KHÔNG sửa tay */
/* Nguồn sự thật: ~/.config/theme/colors/current.conf */

* {
    /* Palette definition */
    background:     #${BG}f2;
    background-alt: #${COLOR0}ee;
    foreground:     #${FG};
    foreground-dim: #${COLOR7};
    selected:       #${ACCENT};
    active:         #${COLOR2};
    urgent:         #${COLOR1};
    border:         #${ACCENT};

    /* Semantic shortcuts */
    bg:             @background;
    bg-alt:         @background-alt;
    fg:             @foreground;
    accent:         @selected;

    background-color: transparent;
    text-color:       @foreground;
}

window {
    border-color:     @border;
    background-color: @background;
}

element selected.normal {
    background-color: @selected;
    text-color:       #${BG};
}

element-text {
    background-color: transparent;
    text-color:       inherit;
}

element-icon {
    background-color: transparent;
}
