! Auto-generated by theme-set — KHÔNG sửa tay
! Nguồn sự thật: ~/.config/theme/colors/current.conf
! Font và alpha được quản lý riêng trong xresources chính

Xft.dpi: ${XFT_DPI}

*.foreground:  #${FG}
*.background:  #${BG}
*.cursorColor: #${FG}

*.color0:  #${COLOR0}
*.color1:  #${COLOR1}
*.color2:  #${COLOR2}
*.color3:  #${COLOR3}
*.color4:  #${COLOR4}
*.color5:  #${COLOR5}
*.color6:  #${COLOR6}
*.color7:  #${COLOR7}
*.color8:  #${COLOR8}
*.color9:  #${COLOR9}
*.color10: #${COLOR10}
*.color11: #${COLOR11}
*.color12: #${COLOR12}
*.color13: #${COLOR13}
*.color14: #${COLOR14}
*.color15: #${COLOR15}

! ==============================================================================
! DWM Semantic Colors (patch/xrdb.c)
! ==============================================================================
dwm.normbgcolor:     #${BG}
dwm.normfgcolor:     #${FG}
dwm.normbordercolor: #${COLOR8}
dwm.normfloatcolor:  #${COLOR8}

dwm.selbgcolor:      #${SURFACE}
dwm.selfgcolor:      #${FG}
dwm.selbordercolor:  #${ACCENT}
dwm.selfloatcolor:   #${ACCENT}

dwm.titlenormbgcolor: #${BG}
dwm.titlenormfgcolor: #${COLOR8}
dwm.titleselbgcolor:  #${BG}
dwm.titleselfgcolor:  #${ACCENT}

dwm.tagsnormbgcolor:  #${BG}
dwm.tagsnormfgcolor:  #${COLOR8}
dwm.tagsselbgcolor:   #${ACCENT}
dwm.tagsselfgcolor:   #${BG}

dwm.hidnormbgcolor:   #${BG}
dwm.hidnormfgcolor:   #${COLOR8}
dwm.hidselbgcolor:    #${SURFACE}
dwm.hidselfgcolor:    #${ACCENT}

dwm.urgbgcolor:       #${COLOR1}
dwm.urgfgcolor:       #${BG}
dwm.urgbordercolor:   #${COLOR1}

! ==============================================================================
! DWM Compatibility / Status2d Colors
! ==============================================================================
dwm.color0:  #${COLOR0}
dwm.color1:  #${COLOR1}
dwm.color2:  #${COLOR2}
dwm.color3:  #${COLOR3}
dwm.color4:  #${COLOR4}
dwm.color5:  #${COLOR5}
dwm.color6:  #${COLOR6}
dwm.color7:  #${COLOR7}
dwm.color8:  #${COLOR8}
dwm.color9:  #${COLOR9}
dwm.color10: #${COLOR10}
dwm.color11: #${COLOR11}
dwm.color12: #${COLOR12}
dwm.color13: #${COLOR13}
dwm.color14: #${COLOR14}
dwm.color15: #${COLOR15}
