! Auto-generated by theme-set — KHÔNG sửa tay
! Nguồn sự thật: ~/.config/theme/colors/current.conf
! Font và alpha được quản lý riêng trong xresources chính

*.foreground:  #${FG}
*.background:  #${BG}
*.cursorColor: #${FG}

*.color0:  #${COLOR0}
*.color1:  #${COLOR1}
*.color2:  #${COLOR2}
*.color3:  #${COLOR3}
*.color4:  #${COLOR4}
*.color5:  #${COLOR5}
*.color6:  #${COLOR6}
*.color7:  #${COLOR7}
*.color8:  #${COLOR8}
*.color9:  #${COLOR9}
*.color10: #${COLOR10}
*.color11: #${COLOR11}
*.color12: #${COLOR12}
*.color13: #${COLOR13}
*.color14: #${COLOR14}
*.color15: #${COLOR15}

! DWM đọc các key dwm.colorN này qua xrdb patch (patch/xrdb.c)
! Mapping: color0=normbg, color6=normfg, color8=border, color14=selbg, ACCENT=border active
dwm.color0:  #${COLOR0}
dwm.color1:  #${COLOR1}
dwm.color2:  #${COLOR2}
dwm.color3:  #${COLOR3}
dwm.color4:  #${COLOR4}
dwm.color5:  #${COLOR5}
dwm.color6:  #${COLOR6}
dwm.color7:  #${COLOR7}
dwm.color8:  #${COLOR8}
dwm.color9:  #${COLOR9}
dwm.color10: #${COLOR10}
dwm.color11: #${COLOR11}
dwm.color12: #${COLOR12}
dwm.color13: #${COLOR13}
dwm.color14: #${COLOR14}
dwm.color15: #${COLOR15}
