[Settings]
# Bộ theme tối tiêu chuẩn, đồng nhất và sạch sẽ
gtk-theme-name=Arc-Gruvbox
gtk-icon-theme-name=Papirus-Dark

# Font chữ hệ thống rõ nét, hiện đại
gtk-font-name=Inter 10

# Đồng bộ con trỏ chuột hệ thống
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=16

# Tắt hình ảnh trên nút bấm và menu để tối giản giao diện và tăng tốc phản hồi
gtk-button-images=0
gtk-menu-images=0
gtk-enable-event-sounds=0
gtk-enable-input-feedback-sounds=0
