[Settings]
# Bộ theme tối tiêu chuẩn, đồng nhất và sạch sẽ
#gtk-theme-name=Arc-Dark
gtk-theme-name=Arc-Gruvbox
gtk-icon-theme-name=Papirus-Dark

# Font chữ hệ thống rõ nét, hiện đại
gtk-font-name=Inter 10

# Đồng bộ con trỏ chuột hệ thống
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=16

# Tắt hình ảnh trên nút bấm và menu để tối giản giao diện và tăng tốc phản hồi
gtk-button-images=0
gtk-menu-images=0
gtk-enable-event-sounds=0
gtk-enable-input-feedback-sounds=0

gtk-toolbar-style=GTK_TOOLBAR_TEXT
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR

gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintmedium
gtk-xft-rgba=rgb
gtk-application-prefer-dark-theme=0
gtk-modules=gail:atk-bridge
