Vertical Candidate List=False
WheelForPaging=True
Font=Inter 10
MenuFont=Inter 10
TrayFont=Inter Bold 10
TrayOutlineColor=#000000
TrayTextColor=#ffffff
PreferTextIcon=False
ShowLayoutNameInIcon=True
UseInputMethodLanguageToDisplayText=True
Theme=default-dark
DarkTheme=default-dark
UseDarkTheme=True
UseAccentColor=True
PerScreenDPI=True
ForceWaylandDPI=0
EnableFractionalScale=True
