Vertical Candidate List=False
WheelForPaging=True
Font=Inter 10
MenuFont=Inter 10
TrayFont=Inter Bold 10
TrayOutlineColor=#000000
TrayTextColor=#ffffff
PreferTextIcon=False
ShowLayoutNameInIcon=False
UseInputMethodLanguageToDisplayText=False
Theme=default-dark
DarkTheme=default-dark
UseDarkTheme=True
UseAccentColor=False
PerScreenDPI=True
ForceWaylandDPI=0
EnableFractionalScale=True
