/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_dwmblocks.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statuscmd.h"
#include "bar_winicon.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_systray.h"

/* Other patches */
#include "attachx.h"
#include "autostart.h"
#include "cfacts.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "movestack.h"
#include "pertag.h"
#include "restartsig.h"
#include "scratchpad.h"
#include "seamless_restart.h"
#include "swallow.h"
#include "vanitygaps.h"
#include "xrdb.h"
/* Layouts */
#include "layout_fibonacci.h"
#include "layout_gapplessgrid.h"
#include "layout_horizgrid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

